config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get :about, to: 'static_pages#about'
resources :password_resets, only:[:new, :create, :edit, :update]
  resources :topics, except: [:show] do
      resources :posts, except: [:show] do
          resources :comments, except: [:show]

       end
     end

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

   end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def index
      @post = Post.includes(:comments).find_by(id: params[:post_id])
      @comments = @post.comments.order("created_at DESC")

    end

    def new
      @post = Post.find_by(id: params[:post_id])
      @comments = Comment.new
    end

    def create

      @post = Post.find_by(id: params[:post_id])
      @comments = Comment.new(comment_params.merge(post_id: params[:post_id]))

      if @comments.save
        flash[:success] = "You've created a new comment."
        redirect_to topic_post_comments_path(@post)
      else
          flash[:danger] = @topic.errors.full_messages
        redirect_to new_topic_post_comments_path(@post)
      end
    end

    def edit
      @comment = Comment.find_by(id: params[:id])
      @post = @comment.post
    end

    def update
      @post = Post.find_by(id: params[:post_id])
      @comment = Comment.find_by(id: params[:id])

      if @comment.update(comment_params)
        flash[:success] = "Comment updated successfully."
        redirect_to topic_post_comments_path(@comment.post)
      else
        redirect_to edit_topic_post_comment_path(@topic,@post, @comment)
      end
    end

    def destroy
      @comment = Comment.find_by(id: params[:id])
      @post = @comment.post

      if @comment.destroy
        redirect_to topic_post_comments_path
      end
    end
    def show
          @comment = Comment.find_by_id(params[:id].to_i)
        end
    private

    def comment_params
      params.require(:comment).permit(:body)
    end
  end

app/views/comments/edit.html.erb
<%= form_for(@comment, url: topic_post_comment_path(@comment), html: { id: "topic-update-form" }) do |f| %>
    <h1 class="text-center">
    Update Comment
    </h1>

    <div class="row">
           <div class="col-lg-4 col-lg-offset-2">
       <div class="form-group">
         <h4> <%= f.label :title_field, "Body" %> </h4>
         <%= f.text_field :body, required: true, id: "comment_title_field", class: 'form-control' %>
         <h5> </h5>
         <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
       </div>
         </div>

  

  <% end %>

app/views/comments/index.html.erb

<div class="background-9">
  <div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="font-title"> LIST COMMENT  </h1>
      </div>
    </div>
   </div>
</div>
<div class="background-14">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-lg-offset-2">
    <h5> Press link "CREATE COMMENT"
      <%= link_to "Create Comment",new_topic_post_comment_path %>
    </h5>
    <h5>
      Press link "BACK TO POST"
      <%= link_to "Back To Post",topic_posts_path %>
    </h5>
  </div>
</div>


</div>


       <div class="col-lg-4 col-lg-offset-2">
 <p> <% @comments.each do |comment| %></p>

   <h3><%= comment.body %></h3>


   <p><%= link_to "Delete Comment", topic_post_comment_path(comment.post.topic,comment.post,comment), method: :delete, data: {confirm: "Are you sure you want to delete?"} %></p>
   <p><%= link_to "Edit Comment", edit_topic_post_comment_path(comment.post.topic,comment.post,comment)%></p>
<% end %>
      </div>
     </div>
    </div>
  </div>
 </div>
</div>
</div>

app/views/comments/new.html.erb

<%= form_for(@comments, url: topic_post_comments_path, html: { id: "comments-create-form" }) do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-left">
      <h2>Create Comment</h2>
    </div>
   </div>
 </div>
 <div class="row">
        <div class="col-lg-4 col-lg-offset-2">
    <div class="form-group">
      <h4> <%= f.label :title_field, "Body" %> </h4>
      <%= f.text_field :body, required: true, id: "comment_title_field", class: 'form-control' %>
    </div>
      </div>


    </div>

      <div class="col-lg-4 col-lg-offset-2 text-center">
        <h4>
        <%= link_to "Back To List",topic_post_comments_path %>
      </h4>
      <%= f.submit "Create comment", class: "btn btn-success btn-lg" %>
    </div>
  <% end %>

app/views/comments/show.html.erb
<h1><%= @comment.body %></h1>
     <%= link_to "Delete", topic_post_comment_path(@comment), method: :delete, data: { confirm: "Delete?" } %>