config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get :about, to: 'static_pages#about'
resources :password_resets, only:[:new, :create, :edit, :update]
  resources :topics, except: [:show] do
      resources :posts, except: [:show] do
          resources :comments, except: [:show]

       end
     end

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  validates :title, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 20 }, presence: true

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]
   def index
      @topics = Topic.all
   end

   def show
     @topic = Topic.find_by(id: params[:id])
   end

   def new
    @topic = Topic.new
    authorize @topic

   end

   def create
      @topic = Topic.new(topic_params)
      if @topic.save
        flash[:success] = "You've created a new topic."
                redirect_to topics_path
      else
        flash[:danger] = @topic.errors.full_messages
        redirect_to new_topic_path
      end
    end
   def edit
      @topic = Topic.find_by(id: params[:id])
   end

   def update
     @topic = Topic.find_by(id: params[:id])

     if @topic.update(topic_params)
         flash[:success] = "Topic updated successfully."
             redirect_to topics_path
       else
      render('edit')

    end
   end

   def destroy
     @topic = Topic.find_by(id: params[:id])
     if @topic.destroy
       redirect_to topics_path
     else
       redirect_to topic_path(@topic)
     end
   end
   private

    def topic_params
      params.require(:topic).permit(:title, :description)
    end
 end

app/views/topics/edit.html.erb
<%= form_for(@topic, url: topic_path(@topic), html: { id: "topic-update-form" }) do |f| %>
    <h1 class="text-center">
      Create Topic
    </h1>

    <div class="form-group">
      <h4> <%= f.label :title_field, "Title" %> </h4>
      <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
    </div>

    <div class="form-group">
      <h4> <%= f.label :text_field, "Description" %> </h4>
      <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
    </div>

    <div class="form-group text-center">
      <%= f.submit "Update Topic", class: "btn btn-success btn-lg" %>
    </div>


  <% end %>

app/views/topics/index.html.erb
<div class="background-8">
  <div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="font-title"> LIST OF TOPIC </h1>
      </div>
    </div>
   </div>
</div>
<div class="background-12">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-lg-offset-2">

        <h4 class="font-word"> Press link "CREATE TOPIC" to create the topic
          <%= link_to "Create Topic",new_topic_path %>
        </h4>
        <h4 class="font-word">***** List of  topic **** </h4>
         <p> <% @topics.each do |topic| %> </p>
         <%= link_to topic.title, topic_posts_path(topic) %>

              <div class="topic">
              <h4 class="font-word"><%= topic.description %></h4>
              <h4 class="font-word">***** Things to Post **** </h4>

                  <%topic.posts.each do |post| %>

      <h4 class="font-word"><%= post.body %></h4>
      <h4 class="font-word">***** Things to Comment **** </h4>
          <%post.comments.each do |comment| %>
            <p> <%= comment.body %></p>


<%end%>
<%end%>

      <p><%= link_to "Delete Topic", topic_path(topic), method: :delete, data: {confirm: "Are you sure you want to delete?"} %></p>
      <p><%= link_to "Edit Topic", edit_topic_path(topic)%></p>

  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/topics/new.html.erb
<%= form_for(@topic, url: topics_path, html: { id: "topic-create-form" }) do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-left">
      <h2>Create Topic</h2>
    </div>
   </div>
 </div>
 <div class="row">
        <div class="col-lg-4 col-lg-offset-2">
<div class="form-group">
      <h4> <%= f.label :title_field, "Title" %> </h4>
      <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
    </div>
      </div>
            </div>
      <div class="row">
              <div class="col-lg-4 col-lg-offset-2">
    <div class="form-group">

      <h4> <%= f.label :text_field, "Description" %> </h4>
      <%= f.text_field :description,required: true, id: "topic_description_field", class: 'form-control' %>
    </div>
    </div>
          </div>

  </div>

    <div class="col-lg-4 col-lg-offset-2 text-center">
      <h4>
      <%= link_to "Back To List",topics_path %>
    </h4>
      <%= f.submit "Create Topic", class: "btn btn-success btn-lg" %>

    </div>
  <% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
    <p><%= @topic.description %></p>
     <%= link_to "Delete", topic_path(@topic), method: :delete, data: { confirm: "Delete?" } %>