config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get :about, to: 'static_pages#about'
resources :password_resets, only:[:new, :create, :edit, :update]
  resources :topics, except: [:show] do
      resources :posts, except: [:show] do
          resources :comments, except: [:show]

       end
     end

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/partials/_flash_messages.html.erb
<div id="flash-messages-container">

<% flash.each do |k,v| %>
   <section class="flash-messages">
     <div class="alert alert-<%=k%>">
       <button type="button" class="close" data-dismiss="alert">
         &times;
       </button>
       <div class="message">
         <%= v %>
       </div>
     </div>
   </section>
 <% end %>
</div>

app/views/partials/_header.html.erb
<nav class="container-fluid">
       <div class="navbar-header">
          <%= link_to "MyForums", root_path, class: "navbar-brand" %>
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-dropdown" aria-expanded="false">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
       </div>
       <div class="collapse navbar-collapse" id="header-dropdown">
         <ul class="nav navbar-nav navbar-right">
          <%if current_user %>

           <li><%= link_to "Topic", topics_path %></li>
           <li><%= link_to "About", about_path %></li>
           <li><%= link_to "Logout", session_path(current_user), method: :delete %></li>
            <% else %>
            <li><%= link_to "Register", new_user_path %></li>
            <li><%= link_to "Login", new_session_path %></li>
             <% end %>

                   </ul>
                   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-dropdown" aria-expanded="false">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                   </button>
       </div>


   </nav>