config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get :about, to: 'static_pages#about'
resources :password_resets, only:[:new, :create, :edit, :update]
  resources :topics, except: [:show] do
      resources :posts, except: [:show] do
          resources :comments, except: [:show]

       end
     end

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :topic, optional: true
  mount_uploader :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

   def index
     @topic = Topic.includes(:posts).find_by(id: params[:topic_id])
     @posts = @topic.posts.order("created_at DESC")

   end

   def new
     @topic = Topic.find_by(id: params[:topic_id])
     @post = Post.new
   end

   def create

     @topic = Topic.find_by(id: params[:topic_id])
     @post = Post.new(post_params.merge(topic_id: params[:topic_id]))

     if @post.save

      flash[:success] = "You've created a new post."

       redirect_to topic_posts_path(@topic)
     else
        flash[:danger] = @topic.errors.full_messages
       redirect_to new_topic_post_path(@topic)
       render 'new'
     end
   end

   def edit
     @post = Post.find_by(id: params[:id])
     @topic = @post.topic
   end

   def update
     @topic = Topic.find_by(id: params[:topic_id])
     @post = Post.find_by(id: params[:id])

     if @post.update(post_params)
       flash[:success] = "Post updated successfully."
       redirect_to topic_posts_path(@post.topic)
     else
       redirect_to edit_topic_post_path(@topic, @post)
     end
   end

   def destroy
     @post = Post.find_by(id: params[:id])
     @topic = @post.topic

     if @post.destroy
       redirect_to topic_posts_path(@topic)
     end
   end
   def show
      @post = Post.find_by_id(params[:id].to_i)
    end
   private

   def post_params
     params.require(:post).permit(:title, :body)
   end
 end

app/views/posts/edit.html.erb
<%= form_for(@post, url: topic_post_path(@post), html: { id: "topic-update-form" }) do |f| %>
    <h1 class="text-center">
      Create Post
    </h1>

    <div class="form-group">
      <h4> <%= f.label :title_field, "Post" %> </h4>
      <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
    </div>

    <div class="form-group">
      <h4> <%= f.label :body_field, "Body" %> </h4>
      <%= f.text_field :body, id: "topic_description_field", class: 'form-control' %>
    </div>

    <div class="form-group text-center">
      <%= f.submit "Update Post", class: "btn btn-success btn-lg" %>
    </div>


  <% end %>

app/views/posts/index.html.erb

<div class="background-8">
  <div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="font-title"> LIST OF POST </h1>
      </div>
    </div>
   </div>
</div>

        <div class="background-12">
          <div class="container">
            <div class="row">
              <div class="col-lg-4 col-lg-offset-2">
    <h5> Press link "CREATE POST"
      <%= link_to "Create Post",new_topic_post_path %>
    </h5>
    <h5>
      Press link "BACK TO POST"
      <%= link_to "Back To Topic",topics_path %>
    </h5>
        <p> <% @posts.each do |post| %>   </p>
          <h5>***** Things to Post**** </h5>
          <%= link_to post.title, topic_post_comments_path(post.topic,post) %>

            <div class="post">
                    <h5><%= post.body %></h5>
                    <h5>***** Things to Comment **** </h5>
                    <%post.comments.each do |comment| %>
                    <p> <%= comment.body %></p>

                    <%end%>

         <p><%= link_to "Delete Post", topic_post_path(post.topic,post), method: :delete, data: {confirm: "Are you sure you want to delete?"} %></p>
         <p><%= link_to "Edit Post", edit_topic_post_path(post.topic,post)%></p>

                    <% end %>
       </div>
     </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_for(@post, url: topic_posts_path, html: { id: "posts-create-form" }) do |f| %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-left">
      <h2>Create Post</h2>
    </div>
   </div>
 </div>
<div class="row">
          <div class="col-lg-4 col-lg-offset-2">
            <div class="form-group">
      <h4> <%= f.label :title_field, "Post" %> </h4>
      <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
    </div>
       </div>
             </div>
       <div class="row">
               <div class="col-lg-4 col-lg-offset-2">
     <div class="form-group">

      <h4> <%= f.label :text_field, "Body" %> </h4>
      <%= f.text_field :body, id: "post_description_field", class: 'form-control' %>
    </div>
      </div>
            </div>

    </div>

      <div class="col-lg-4 col-lg-offset-2 text-center">
        <h4>
        <%= link_to "Back To List",topic_posts_path %>
      </h4>
      <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
    </div>
  </div>
  <% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
    <p><%= @post.description %></p>
     <%= link_to "Delete", topic_post_path(@post), method: :delete, data: { confirm: "Delete?" } %>